server:
  port: 8082

sdk:
  config:
    base-uri: "https://api-test.ksef.mf.gov.pl"
    suffix-uri: "v2"
    qr-uri: "https://qr-test.ksef.mf.gov.pl"
    request-timeout: 100

spring:
  profiles:
    default: local
